#!/bin/bash

base_packages="base base-devel linux linux-headers linux-firmware grub sudo nano networkmanager ufw iwd efibootmgr"
kde_packages="plasma-meta plasma-wayland-session pulseaudio sddm network-manager-applet xorg konsole"
gnome_packages="gnome pulseaudio gdm network-manager-applet xorg gnome-terminal"
xfce_packages="lightdm lightdm-gtk-greeter xfce4 network-manager-applet xorg"
mate_packages="lightdm lightdm-gtk-greeter mate network-manager-applet xorg mate-terminal"
disk=""
root=""
efi=""
timezone="Europe/Madrid"
hostname="arch"
username="user"
sudoer="Y"
desktop="kde"

Installer () {
    echo "Welcome to the Arch Linux Installer by hhk02!"
    lsblk
    read -r -p "Write your disk : " disk
    if [ -z "$disk" ]; then
        echo "Please specify a disk!"
        read -r -p "Write your disk : " disk
    else
        echo "Disk selected : " "$disk"
        fdisk "$disk"
    fi
    read -r -p "Please specify your EFI paritition :" efi
    if [ -z "$efi" ]; then
        echo "Please specify the efi!"
        read -r -p "Write your efi partition : " efi
    else
        echo "Partition selected : " "$efi"
        mkfs.vfat -F 32 "$efi"
        echo "Done!"
    fi
    read -r -p "Please specify your root paritition : " "root"
    if [ -z "$root" ]; then
        echo "Please specify the root partition!"
        read -r -p "Write your root partition : " "root"
    else
        echo "Partition selected : " "$root"
        mkfs.ext4 "$root"
        echo "Done!"
    fi
    clear
    echo "Mounting necessary partitions!"
    mkdir -p /mnt/boot
    mount "$root" /mnt
    mount "$efi" /mnt/boot
    echo "Done!"
    clear
    echo "Installing base packages...."
   
    pacstrap /mnt "$base_packages"
    echo "Generating fstab...."
    genfstab -U /mnt > /mnt/etc/fstab
    echo "Done!"
    echo "Installing bootloader"
    arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot
    arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
    echo "Done!" 
    echo "Change the root password!"
    arch-chroot /mnt passwd root
    echo "Done!"
    echo "Adding a non-root user...."
    read -r -p "Name of the user: " "username"

    if [ -z "$username" ]; then
        echo "Please specify a username!"
        read -r -p "Name of the user: " username
    else
        echo "Selected username: " "$username"
    fi    
    arch-chroot /mnt useradd -m "$username"
    echo "Now the password:"
    arch-chroot /mnt passwd "$username"
    echo "Done"
    read -r -p "You need this user make a sudoer? (Y/N)" "sudoer"

    if [ -z "$sudoer" ]; then
        read -r -p "You need this user make a sudoer? (Y/N)" "sudoer"
    fi

    if [ "$sudoer" = "Y" ]; then
        echo "Make this user sudoer: " "$username"
        echo "Adding to sudo group...."
        arch-chroot /mnt usermod -aG wheel "$username"
        echo "Done"
    else
        echo "The user decided make this user without root permissions!"
        echo "Done!"
    fi

    read -r -p "Write the hostname: default: arch " "hostname"

    if [ -z "$hostname" ]; then
        echo "Using the default value!"
        arch-chroot /mnt hostnamectl set-hostname "$hostname"
        echo "Done!"
    else
        echo "Setting hostname..."
        echo "$hostname" > /mnt/etc/hostname
        echo "Done!"
    fi
    read -r -p "Write your timezone" "timezone"
    if [ -z "$timezone" ]; then
       read -r -p "Write your timezone" "timezone"
    else
        echo "Setting timezone to : " "$timezone"
    fi 

    read -r -p "What desktop you do want? (kde/gnome/xfce/mate?)" "desktop"
    if [ -z "$desktop" ]; then
        echo "Using the default value!"
    else
        if [ "$desktop" = "kde" ]; then
            echo "Selected KDE..."
            pacstrap /mnt "$kde_packages"
            mkinitcpio -p linux
            echo "Enabling systemd PD: Eh ahi la importancia de systemd :v"
            arch-chroot /mnt systemd-firstboot
            arch-chroot /mnt systemctl enable NetworkManager
            arch-chroot /mnt systemctl enable sddm
            echo "Done!"
        fi
        if [ "$desktop" = "gnome" ]; then
            echo "Selected GNOME..."
            pacstrap /mnt "$gnome_packages"
            mkinitcpio -p linux
            echo "Enabling systemd pd: he ahi la importancia de systemd :v"
            arch-chroot /mnt systemd-firstboot
            arch-chroot /mnt systemctl enable NetworkManager
            arch-chroot /mnt systemctl enable gdm
            echo "Done!"
        fi
        if [ "$desktop" = "xfce" ]; then
            echo "Selected XFCE..."
            pacstrap /mnt "$xfce_packages"
            mkinitcpio -p linux
            echo "Enabling systemd pd: he ahi la importancia de systemd :v"
            arch-chroot /mnt systemd-firstboot
            arch-chroot /mnt systemctl enable NetworkManager
            arch-chroot /mnt systemctl enable lightdm
            echo "Done!"
        fi
        if [ "$desktop" = "mate" ]; then
            echo "Selected MATE..."
            pacstrap /mnt "$mate_packages"
            mkinitcpio -p linux
            echo "Enabling systemd pd: he ahi la importancia de systemd :v"
            arch-chroot /mnt systemd-firstboot
            arch-chroot /mnt systemctl enable NetworkManager
            arch-chroot /mnt systemctl enable lightdm
            echo "Done!"
        fi
    fi

    echo "Change the locale settings!"
    nano /mnt/etc/locale.conf
    nano /mnt/etc/locale.gen
    echo "Generating locale..."
    locale-gen
    echo "Done!"
    clear
    echo "Installation complete! please reboot your computer with systemctl reboot or init 6"
}

if [ $EUID -eq 0 ]; then
    Installer
else
    echo "ERROR: PLEASE RUN THIS AS ROOT!"
fi